// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDRgW2W-bX5DJtt2wVwqNEwEWvYkJXZgq8',
  //   appId: '1:1008806610906:web:ff2d577b5c33d9447722e3',
  //   messagingSenderId: '1008806610906',
  //   projectId: 'umi1-7b2c9',
  //   authDomain: 'umi1-7b2c9.firebaseapp.com',
  //   storageBucket: 'umi1-7b2c9.firebasestorage.app',
  //   measurementId: 'G-2SY0PX6BS4',
  // );
  //
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9fkwLa43rvEXPdIiHolUqULPX_4MOoiU',
    appId: '1:1008806610906:android:f071bd2dda461f4d7722e3',
    messagingSenderId: '1008806610906',
    projectId: 'umi1-7b2c9',
    storageBucket: 'umi1-7b2c9.firebasestorage.app',
  );
  //
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAm06LESW_Iio4YSrIueFrtrWfsqMKC6xM',
  //   appId: '1:1008806610906:ios:64fe6b15e3b997067722e3',
  //   messagingSenderId: '1008806610906',
  //   projectId: 'umi1-7b2c9',
  //   storageBucket: 'umi1-7b2c9.firebasestorage.app',
  //   iosBundleId: 'com.sixamtech.stackfoodUserAppDevMehedi',
  // );
}
